### ISSUE TITLE
你好，请问你也是用django-allauth实现auth的吗

### ISSUE THREAD

**Issue by BadGrem** [Hopetree/izone#10]
我有一个疑问，就是关于"Remember Me"这个CheckBox的，默认是不是没有利用cookie实现用户信息的保存？这个需要自己实现吗？

**Comment by Hopetree** [comment]
@BadGrem 实际上django-allauth做的只是第三方的登录，cookie这些东西其实还是django自带的来做的，默认就是会保存的

**Comment by Justin3go** [comment]
请问，记住我这个字段后台是在哪里设置的，

**Comment by Justin3go** [comment]
请问，记住我这个字段是在后台哪个字段设置的，我想在前端单独给它设置样式，但好像不行

**Comment by Justin3go** [comment]
请问，”记住我“这个字段是在后台哪个地方设置的，我想为它单独设置个样式，但好像不行，没找到
