### ISSUE TITLE
是不是改了分支名字？v2该用哪个分支？

### ISSUE THREAD

**Issue by Sumzibuyu** [Hopetree/izone#111]
是不是改了分支名字？v2该用哪个分支？

**Comment by Sumzibuyu** [comment]
## v2-1已经大半年没更新了  我要手动上传安装  应该用哪个分支 胡总tag才是最新的呢？3.1.1和2.1.10又是什么呢？

**Comment by Hopetree** [comment]
按照知道wiki来
