### ISSUE TITLE
页面出现抖动的情况

### ISSUE THREAD

**Issue by anshingy** [Hopetree/izone#117]
当页面出现滚动条，滚动到最下面，刷新网页时整个页面出现抖动情况，上下抖动； 当页面内容不是很多，出现滚动条且可直接看到底部栏时，刷新网页整个页面出现左右抖动。

**Comment by Hopetree** [comment]
你说的这个抖动是页面加载的瞬间吧，如果是的话，这个属于正常现象啊

**Comment by anshingy** [comment]
@Hopetree  刷新时滚动条快速滚动一下，造成整个页面上下抖动。这可能与刷新页面时滚动条由最开始滚动到上一次的位置有关。  另外，滚动条没有出现到出现时造成页面左右抖动。当页面内容很多时刷新页面则不会出现抖动情况。

**Comment by Hopetree** [comment]
@anshingy 没错，是这样的，因为我博客的刷新不是异步加载新内容而是整体刷新，所以会感觉到比较明显的刷新效果，也就是你说的抖动情况，但是并不影响用户体验
