### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by qiutzh** [Hopetree/izone#121]
如题，这个错误是在执行python manage.py makemigrations时出现的，没有其它提示，请问有遇到过吗？怎么解决啊？

**Comment by Hopetree** [comment]
遇到问题先自己通过搜索引擎去查，你这个报错我没遇到过，但是我查了一下，跟linux内存有关，所以建议看看自己的虚拟机配置，如果用mysql的话，内存应该不能小于500M

**Comment by qiutzh** [comment]
多谢哈！把虚拟机内存从2G改到4G这个错还是有的。

之后用strace命令跟踪了下 python manage.py makemigrations 的执行情况
[log.txt](https://github.com/Hopetree/izone/files/4980424/log.txt)

还是不清楚什么原因造成的。好迷茫~  对了，我是用的master那个版本，django是2.0的。

**Comment by qiutzh** [comment]
使用的版本不对，已经解决了，感谢！^_^
