### ISSUE TITLE
我在 adminx 添加文章 的时候报了一个错误提示

### ISSUE THREAD

**Issue by ybscj** [Hopetree/izone#124]
ubuntu上的本地运行(python manage.py runserver)添加并保存文章是没问题的

唯独django+nginx+wsgi运行的时候 在 adminx 后台编辑好文章, 点击保存时报了这个错误

不知道该怎么解决

OSError at /adminx/blog/article/add/
The path to your Whoosh index '/var/www/web/izone/whoosh_index' is not writable for the current user/group.

**Comment by ybscj** [comment]
> ubuntu上的本地运行(python manage.py runserver)添加并保存文章是没问题的
> 
> 唯独django+nginx+wsgi运行的时候 在 adminx 后台编辑好文章, 点击保存时报了这个错误
> 
> 不知道该怎么解决
> 
> OSError at /adminx/blog/article/add/
> The path to your Whoosh index '/var/www/web/izone/whoosh_index' is not writable for the current user/group.

**Comment by Hopetree** [comment]
/var/www/web/izone/whoosh_index 目录的用户权限不够，给目录加一下用户权限即可
