### ISSUE TITLE
import问题

### ISSUE THREAD

**Issue by xiaolaohu88** [Hopetree/izone#13]
运行python3 manage.py makemigrations的时候总是说没有模块，pip3安装后，还是有新模块未安装，是不是有个模块包？
网站主能否把安装网站的教程写详细点或录制视频，小白求教，以后安装上了帮你宣传，嘻嘻

**Comment by Hopetree** [comment]
@xiaolaohu88 项目是在虚拟环境中运行的，有一个安装依赖的文件，你先去看我那篇关于虚拟环境的文章，弄好了环境再安装运行就简单了
