### ISSUE TITLE
# 后台markdown编辑器改为使用 django-mdeditor  

### ISSUE THREAD

**Issue by moyueheng** [Hopetree/izone#169]
由于本来的 markdown没有预览功能，也不能直接上传文件之类的，使用体验效果不好，可以改成 django-mdeditor  吗

**Comment by Hopetree** [comment]
@moyueheng 可以自行拉代码到你项目中修改，我项目目前不打算集成编辑器，因为有工具专门可以用来编辑文章，而图片上传我比较倾向于云管理，而不是存在本地服务器，不然带宽不够

**Comment by moyueheng** [comment]
请问您的专门工具是什么
