### ISSUE TITLE
请问打开文章之后，没有显示侧面悬浮的文章目录吗

### ISSUE THREAD

**Issue by liuqiao1995** [Hopetree/izone#183]

**Comment by Hopetree** [comment]
> 

之前有目录，我隐藏了，你可以在代码里面找到应该

**Comment by algorithm007** [comment]
这个目录的布局应该怎么写啊？

**Comment by Hopetree** [comment]
@liuqiao1995 @algorithm007 博客的文章导航我又打开了，前端页面也简单调整了一下，可以看看效果，其实后端一致都是有目录的，只是前端之前被我注视了，可以看最近跟新的文章页面的修改，还有一点点导航相关的css

**Comment by liuqiao1995** [comment]
好的，非常感谢
