### ISSUE TITLE
SyntaxError: Generator expression must be parenthesized

### ISSUE THREAD

**Issue by natsume37** [Hopetree/izone#284]
运行：python manage.py makemigrations后
<img width="981" alt="image" src="https://github.com/Hopetree/izone/assets/103176271/70266acd-d063-4f14-a681-69fa7b12faf2">

**Comment by Hopetree** [comment]
@natsume37 你安装的依赖是我项目里面requirements.txt的吗，我怀疑你这个是依赖的版本问题
