### ISSUE TITLE
运行指导是否更新下

### ISSUE THREAD

**Issue by onefoxjump** [Hopetree/izone#288]
比如适用的python版本、Django版本等，以及详细的部署过程。

**Comment by Hopetree** [comment]
@onefoxjump 见博客的这篇文章，文章会持续更新，https://tendcode.com/subject/article/izone-install-docs/

**Comment by onefoxjump** [comment]
@Hopetree 谢谢回复。目前正在学习Django，能否详细讲解下此项目是如何设计的、项目结构以及不通过docker部署的方式？比如：1.项目的开发环境 2.创建APP 3.编写model 4.View及Template ……最后项目部署等等。

**Comment by Hopetree** [comment]
> @Hopetree 谢谢回复。目前正在学习Django，能否详细讲解下此项目是如何设计的、项目结构以及不通过docker部署的方式？比如：1.项目的开发环境 2.创建APP 3.编写model 4.View及Template ……最后项目部署等等。

你要一个比较完整的开发过程的教程的话，可以在网上找一下，博客教程还挺多的，我就没心思再去单独写一个教程了
