### ISSUE TITLE
weibo登录报错，怎么改用自己的key?

### ISSUE THREAD

**Issue by caoliang12121** [Hopetree/izone#29]

**Comment by Hopetree** [comment]
@caoliang12121 
微博需要先去他们开发者平台申请ID，然后可以得到跟GitHub一样的key，填入到后台中即可

**Comment by caoliang12121** [comment]
能说一下哪里吗？我没找到你填微博key的地方~

**Comment by caoliang12121** [comment]
> @caoliang12121
> 微博需要先去他们开发者平台申请ID，然后可以得到跟GitHub一样的key，填入到后台中即可
