### ISSUE TITLE
adminx 错误

### ISSUE THREAD

**Issue by dijiudu** [Hopetree/izone#3]
我把django 模块升级到 django2.04 ，下面这些命令均已完成
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
但是出现这个跳转
http://127.0.0.1:8000/adminx/login/?next=/adminx/
Server Error (500)

**Comment by Hopetree** [comment]
@dijiudu 你这个应该就是我说过的，django2.0的路由改动了，所有你首先要按照2.0的路由的设置方式去改urls.py的内容
