### ISSUE TITLE
评论与回复消息无通知

### ISSUE THREAD

**Issue by boyl** [Hopetree/izone#4]
博主代码应该是在app.py少了import signals

**Comment by Hopetree** [comment]
@boyl 回复没有问题，评论是否回复是有判断条件的，比如自己评论自己不会收到，你可以看我具体的信号判断

**Comment by boyl** [comment]
那部分代码我看了。我注册两个账号测试过了，确实收不到评论信息。当我在ready方法中import 自定义的那个handlers文件后就可以了。

**Comment by Hopetree** [comment]
@boyl 我的comment下面的views.py中引入了这个类的，我项目运行没有问题，可以正常收到信息，不信去去我博客中留言，我给你回复一个
```
from . import handlers
```

**Comment by boyl** [comment]
ok, 谢谢解答
