### ISSUE TITLE
缓存问题，关于timeline

### ISSUE THREAD

**Issue by boyl** [Hopetree/izone#5]
博主，我在新建timeline内容后，页面无法把内容显示出来
![image](https://user-images.githubusercontent.com/30596191/39977690-3a31283a-576e-11e8-9bc6-81efc5e7725b.png)去掉cache就可以了，这个问题有遇见过吗

**Comment by boyl** [comment]
额，我已经清楚了-。-

**Comment by Hopetree** [comment]
@boyl 有很多地方我设置了缓存，因为没必要实时更新，你可以看源码，不仅仅是timeline，还有右边分类，推荐工具、归档等等地方都有，只要是不需要实时更新的都可以设置一定的缓存

**Comment by boyl** [comment]
@Hopetree 嗯嗯
