### ISSUE TITLE
markdown的数学公式

### ISSUE THREAD

**Issue by zhurboo** [Hopetree/izone#58]
您好，我用了你的v1版本，发现文章内无法使用数学公式，如（$...$） 。
想问一下是不是我的操作不对~

**Comment by Hopetree** [comment]
不是操作的问题，是本身就不支持，数学公式是扩展语法，markdown本身是不支持的，这个只支持原生的一些语法

**Comment by zhurboo** [comment]
有什么办法添加相关支持吗？
我试了几个方法均失败了。
如https://github.com/bauripalash/pydjax

**Comment by Hopetree** [comment]
我之前其实尝试过拓展这个markdown，但是由于依赖的版本出现了问题所以放弃了，不过可以给你提供思路：

首先，我博客里面的markdown是使用的第三方库进行转化的，所以怎么让这个库支持更多扩展语法是关键，你可以找一下这个库的扩展库（是存在的，我找到过，有很多扩展语法可以用），装了扩展库之后在转化的时候增加语法支持的扩展就可以了（这种方法我试过，单独在python脚本没有问题，但是我放到django这里出了问题，记得好像是依赖的库之间的版本出现了问题）

还有一种方法，那就是你重新找一个能支持更多语法的markdown转化的库取代我现在用的这个

还有一种方法：可以让渲染markdown 的过程不在后端实现，而是由前端实现，同样你需要找前端的渲染方法

**Comment by zhurboo** [comment]
感谢，已经使用Mathjax简单得从前端解决了。
不过这样使得原生的Latex语法需要稍微修改，有点麻烦。
