### ISSUE TITLE
关于开发环境使用django-allauth

### ISSUE THREAD

**Issue by boyl** [Hopetree/izone#6]
开发环境127.0.0.1：8000，我第一次使用GitHub能登陆成功，之后再次尝试都会在回转的时候报错，报错如下：
![image](https://user-images.githubusercontent.com/30596191/40152600-785e1a18-59b8-11e8-99cc-a2b5082026a4.png)
之后，我尝试在后台删除秘钥，同时在GitHub新增app并把秘钥加入网站后台，错误如出一辙，看了开发控制台，如下：
![image](https://user-images.githubusercontent.com/30596191/40152693-d0af3706-59b8-11e8-83ce-70ee1e646023.png)
同时附上GitHub app配置，如下：
![image](https://user-images.githubusercontent.com/30596191/40152752-18cd3948-59b9-11e8-9d60-912202937346.png)
博主，我这是啥问题呀，开发环境能ok吗？

**Comment by Hopetree** [comment]
@boyl 开发环境是没有问题的，你看一下你的后台设置的“站点”，要让ID为2的站点是你http://127.0.0.1:8000，因为我在设置里面的SITE_ID = 2，你看看你是不是有添加一个域名，默认应该是example.com，那个可以不用管。然后在Social applications中你添加GIT的里面添加你设置的http://127.0.0.1:8000到“选中的 sites”

**Comment by boyl** [comment]
@Hopetree 
![image](https://user-images.githubusercontent.com/30596191/40219516-4a896674-5aa8-11e8-8048-b005bd449979.png)这个应该是授权后自动生成才对。
![image](https://user-images.githubusercontent.com/30596191/40219534-6885e6a2-5aa8-11e8-98f9-6b3fa179a0a9.png)
我现在设置的SITE_ID=3
![image](https://user-images.githubusercontent.com/30596191/40219563-90bf0f18-5aa8-11e8-9b0b-96ea454a7c93.png)
这是github应用站点配置。因为我照着来重新敲打的，不知是不是漏了哪些操作。

**Comment by boyl** [comment]
@Hopetree emm很奇怪，我只是打开截了一下图，然后试了一下，能上了（没做任何改动！！！）
![image](https://user-images.githubusercontent.com/30596191/40219685-109bb402-5aa9-11e8-9485-70e75128a837.png)

**Comment by boyl** [comment]
我对比了下登陆不成功的后台（上面有截图），成功截图如下：
![image](https://user-images.githubusercontent.com/30596191/40219790-727afa20-5aa9-11e8-8dbe-cd07294aff8f.png)
他多了个状态 200

**Comment by boyl** [comment]
谢谢博主
