### ISSUE TITLE
创建数据库报错

### ISSUE THREAD

**Issue by nineaiyu** [Hopetree/izone#7]
能否把数据库的版本及数据库 my.cnf 配置文件发下看看，每当我执行创建数据库时 django.db.utils.InternalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')  都会有这个错误

**Comment by Hopetree** [comment]
@我的数据库是5.7的版本，创建数据库的时候编码格式设置成utf8mb4，你看我readme里面有写我创建数据的命令，不过我记得低版本不支持这个格式，你可以查查你的版本支不支持这个格式，如果不支持，你就别用MySQL了，用自带的数据库得了，或者换个版本，配置文件我没有改动过，就是默认的

**Comment by n37r06u3** [comment]
pymysql.err.InternalError: (1071, 'Specified key was too long; max key length is 767 bytes')

venv/lib/python3.6/site-packages/allauth/account/migrations/0002_auto_20180608_1035.py

同错

**Comment by n37r06u3** [comment]
测试用utf8不会报错

CREATE DATABASE `izone` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
