### ISSUE TITLE
有没有考虑将django升到2.0+

### ISSUE THREAD

**Issue by wardseptember** [Hopetree/izone#72]
有没有考虑将django升到2.0+

**Comment by Hopetree** [comment]
暂时没有这个考虑，因为升级到2.0其实对于django本身需要改的东西不多，但是由于项目涉及的其他依赖比较多，而且依赖之间有版本要求，所以升级django很可能引起其他依赖出现问题，所以暂时不考虑

**Comment by Hopetree** [comment]
目前尝试升级到django2.x最新版，需要规避的问题如下：
1. 所有的依赖包都需要丢弃现有版本，直接安装最新版，目前发现依赖包兼容都是OK的
2. 需要添加所有model中关联模型的on_delete缺失的参数，根据实际情况填写
3. urls.py中有namespace的需要将include第一个参数换成元祖，特别注意include((router.urls,router.root_view_name),namespace='api')
4. 替换现有的templates为新版本对应的模板，包括boostrap_admin和drf的，account的暂时没有发现问题，需要检验

**Comment by Hopetree** [comment]
@anshingy 
@wardseptember 
博客已经升级到 django2.1.4

**Comment by wardseptember** [comment]
谢谢你，哈哈哈
@Hopetree

**Comment by anshingy** [comment]
@Hopetree 非常感谢，博客很漂亮准备再次入手试试

**Comment by zhuzhao** [comment]
哈哈哈，不错
