### ISSUE TITLE
微博第三方登录问题

### ISSUE THREAD

**Issue by wardseptember** [Hopetree/izone#84]
你好，我已经在后台social application添加微博登录应用了，为什么一直报SocialApp matching query does not exist.
回调地址设置的[http://www.wardseptember.top/accounts/weibo/login/callback/](http://www.wardseptember.top/accounts/weibo/login/callback/)
github授权可以。更改site_id也不行。

**Comment by Hopetree** [comment]
@wardseptember sites选择的是当前域名没错吧，这个域名在站点里面的ID是不是跟你settings文件中设置的站点ID是一致的

**Comment by wardseptember** [comment]
@Hopetree 谢谢你，sites里域名忘记设置了。
